# Generated by Django 3.0.5 on 2020-05-18 15:43

from django.db import migrations, models
import django.db.models.deletion
import referral_sample.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=64)),
                ('phone', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('state', models.PositiveSmallIntegerField(default=0)),
                ('taken', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='referral_sample.SessionUser')),
            ],
        ),
    ]
