# Generated by Django 3.0.5 on 2020-05-19 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('referral_sample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=64)),
                ('phone', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='sessionuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sessionuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='sessionuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='sessionuser',
            name='phone',
        ),
        migrations.AddField(
            model_name='sessionuser',
            name='session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sessions.Session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessionuser',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='referral_sample.Booking'),
        ),
    ]
