# Generated by Django 3.0.5 on 2020-05-19 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0004_auto_20200519_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking_system.Booking'),
        ),
    ]
